
spring:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/race-manager?useSSL=false
    username: pduser
    password: pdpassword
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:db/data-dev.sql

server:
  port: 8090